define([], function () {
  return {
    WeeksOnLabel: "semanas(s) on",
    PaternLabel: "Pattern",
    OcurrencesLabel: "Ocurrences",
    dateRangeLabel: "Rango de Fechas",
    weekEndDay: "Weekend Day",
    weekDayLabel: "Días de la semana",
    lastLabel: "Último",
    fourthLabel: "cuarto",
    thirdLabel: "tercero",
    secondLabel: "segundo",
    firstLabel: "primero",
    theLabel: "el",
    MonthsLabel: "mes(s)",
    ofEveryLabel: "De cada ",
    AllowedValues1to12Label: "Valores permitidos del 1 al 12",
    noEndDate: "Sin fecha de finalización",
    everyweekdays: "Todos los días de la semana",
    days: "días",
    every: "cada",
    EndByLabel: "finalización",
    EndAfterLabel: "termina después",
    HttpErrorMessage: "Error al leer eventos del calendario:",
    CategoryPlaceHolder: "Selecciona una categoría",
    CategoryLabel: "Categoría",
    EnDateValidationMessage: "la fecha de inicio es mayor que la fecha de finalización",
    SartDateValidationMessage: "la fecha de inicio es mayor que la fecha de finalización",
    eventSelectDatesLabel: "Mostrar solo los eventos dentro de las siguientes fechas",
    ConfirmeDeleteMessage: "Confirmar eliminar evento? Si el evento es un evento recurrente, todas las entradas se eliminarán ",
    DialogConfirmDeleteTitle: "Eliminar Evento",
    SpinnerDeletingLabel: "Eliminando...",
    DialogCloseButtonLabel: "Cancelar",
    DialogConfirmDeleteLabel: "Eliminar",
    SaveButtonLabel: "Guardar",
    DeleteButtonLabel: "Eliminar",
    CancelButtonLabel: "Cancelar",
    LoadingEventsLabel: "Cargando eventos...",
    WebPartConfigButtonLabel: "Configurar",
    WebpartConfigDescription: "Configura la lista de calendario ",
    WebpartConfigIconText: "Configurar Calendario Componente",
    EventOwnerLabel: "Dueñ@ del Evento",
    InvalidDateFormat: "Formato de fecha inválido.",
    IsRequired: "Campo requerido.",
    CloseDate: "Selector de fecha de cierre",
    NextYear: "Ir al próximo año",
    PrevYear: "Ir al previo año",
    NextMonth: "Ir al próximo mes",
    PrevMonth: "Ir al previo año",
    GoToDay: "ir a Hoy",
    ShortDay_Saunday: "S",
    ShortDay_Friday: "F",
    ShortDay_Tursday: "T",
    ShortDay_W: "W",
    ShortDay_T: "T",
    ShortDay_M: "M",
    ShortDay_S: "S",
    Saturday: "Saturday",
    Friday: "Friday",
    Thursday: "Thursday",
    Wednesday: "Wednesday",
    Tuesday: "Tuesday",
    Monday: "Monday",
    Sunday: "Sunday",
    Jan:"Jan",
    Feb:"Feb",
    Mar:"Mar",
    Apr:"Apr",
    May:"May",
    Jun:"Jun",
    Jul:"Jul",
    Aug:"Aug",
    Sep:"Sep",
    Oct:"Oct",
    Nov:"Nov",
    Dez:"Dez",
    December: "December",
    November: "November",
    October: "October",
    September: "September",
    August: "August",
    July: "July",
    June: "June",
    May: "May",
    April: "April",
    March: "March",
    February: "February",
    January: "January",
    LocationLabel: "Location search and Map",
    LocationTextLabel: "Location",
    AttendeesLabel: "Attendees",
    EndMinLabel: "Min",
    EndHourLabel: "Hour",
    EndDateLabel: "End Date",
    EndDatePlaceHolder: "Select a date...",
    StartMinLabel: "Min",
    StartHourLabel: "Hour",
    StartDateLabel: "Start Date",
    StartDatePlaceHolder: "Select a date...",
    EventTitleErrorMessage: "Event Title is required.",
    EventTitleLabel: "Event title",
    EventPanelTitle: "Edit/Add Event",
    PropertyPaneDescription: "Calendar",
    BasicGroupName: "Properties",
    SiteUrlFieldLabel: "Site Url",
    ListFieldLabel: "Calendar List name",
    weekLabel: "Week",
    dayLable: "Day",
    agenda: "Agenda",
    monthLabel: "Month",
    todayLabel: "Today",
    previousLabel: "Previous",
    nextLabel: "Next",
    showMore: "more",
    recurrenceEventLabel: "Recurrence Event",
    editRecurrenceSeries: "Edit Recurrence Series",
    ifRecurrenceLabel: "Recurrence ?",
    onLabel: "On",
    offLabel: "Off",
    eventDescriptionLabel: "Event Description",
    recurrenceInformationLabel: "Recurrence Information",
    dailyLabel: "Daily",
    weeklyLabel: "Weekly",
    monthlyLabel: "Monthly",
    yearlyLabel: "Yearly",
    patternLabel: "Pattern",
    dateRangeLabel: "Date Range",
    occurrencesLabel: "occurrences",
    ofMonthLabel: "of",
    everyFormat: "Every {0} ",
    everySecondFormat: "Every {0} ",
    everyNthFormat: "Every {0} ",
    onTheDayFormat: "on the {0}th day",
    onTheLabel: "on the",
    theSuffix: "",
    yearLabel: "year",
    theNthOfMonthFormat: "on {0} {1}",
    onTheDayTypeFormat: "on the {0} {1}"
  }
});
